# -*- coding: utf-8 -*-
"""inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DI1uN-LZ5GLqha-6SZ28J3WlVtZhdkR_
"""

import os
import torch
import sys
from unsloth import FastLanguageModel
from peft import PeftModel

def initialize_model():
    """
    Initializes the base architecture and wraps it with the Stage 3 DPO adapter.
    """
    max_seq_length = 2048
    dtype = torch.float16
    load_in_4bit = True

    # Path to your final, persistent Stage 3 DPO-aligned adapter folder on Drive
    dpo_adapter_path = "/content/drive/MyDrive/domain-ai-assistant-models/stage3_dpo_adapter"

    if not os.path.exists(dpo_adapter_path):
        print(f"❌ Error: Could not locate the DPO adapter directory at: {dpo_adapter_path}")
        print("Please verify that your Google Drive is mounted and the folder path is accurate.")
        sys.exit(1)

    print("📥 Initializing foundational base framework layer...")
    base_model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "unsloth/Qwen2.5-1.5B",
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )

    print(f"🔄 Layering Stage 3 DPO preference adapter from: {dpo_adapter_path}")
    model = PeftModel.from_pretrained(base_model, dpo_adapter_path)

    # Switch the complete network matrix into Unsloth's highly optimized 2x faster inference state
    FastLanguageModel.for_inference(model)

    return model, tokenizer

def generate_answer(question: str, model, tokenizer) -> str:
    """
    Formats the input question, runs tokenization, and returns the aligned model answer.
    """
    prompt_template = """Below is an instruction that describes a financial question. Write a response that appropriately answers the request.

### Instruction:
{}

### Response:
"""

    formatted_prompt = prompt_template.format(question)
    inputs = tokenizer([formatted_prompt], return_tensors="pt").to("cuda")

    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        use_cache=True,
        temperature=0.1,  # Kept low to guarantee deterministic, highly factual banking guidance
        top_p=0.9
    )

    generated_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

    response_marker = "### Response:\n"
    if response_marker in generated_text:
        answer = generated_text.split(response_marker)[1].strip()
    else:
        answer = generated_text.replace(formatted_prompt, "").strip()

    return answer

if __name__ == "__main__":
    # Disable background JIT compiling to ensure stability across Colab container environments
    os.environ["UNSLOTH_COMPILE_DISABLE"] = "1"

    # Initialize the model and tokenizer
    model, tokenizer = initialize_model()

    print("\n" + "="*50)
    print("🎉 Card Domain AI Assistant Online!")
    print("Ask any question regarding credit cards, debit cards, or banking protocols.")
    print("Type 'quit' or 'exit' to stop the session.")
    print("="*50 + "\n")

    # Interactive Console Loop
    while True:
        try:
            user_question = input("❓ Enter your card question: ").strip()

            # Check for exit commands
            if user_question.lower() in ['quit', 'exit']:
                print("\n👋 Closing assistant session. Goodbye!")
                break

            # Skip empty entries
            if not user_question:
                continue

            print("🤖 Generating aligned domain response...")
            answer = generate_answer(user_question, model, tokenizer)

            print(f"\n💡 Answer:\n{answer}")
            print("-" * 50 + "\n")

        except KeyboardInterrupt:
            print("\n👋 Session interrupted. Goodbye!")
            break

